apiVersion: v1
kind: Service
metadata:
  name: web-api-node
spec:
  type: NodePort
  selector:
    app: web-api
    release: stable
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
