apiVersion: v1
kind: Service
metadata:
  name: web-ui-node
spec:
  type: NodePort
  selector:
    app: web-ui-client
    release: stable
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
