apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-api
      release: stable
  template:
    metadata:
      name: web-api
      labels:
        app: web-api
        release: stable
        created_by: trung.tran
    spec:
      containers:
        - name: web-api
          image: k8s-learning.docker.io/web-api:1.0.2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
