apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      release: stable
  template:
    metadata:
      name: worker
      labels:
        app: worker
        release: stable
        created_by: trung.tran
    spec:
      containers:
        - name: worker
          image: k8s-learning.docker.io/worker
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128M"
              cpu: "500m"
          env:
            - name: WebApiUrl
              value: http://web-api
