name: docker-learning-app

include:
  - path: ./compose.infras.yaml

services:
  web-api:
    build:
      context: ./my-be-api
    ports:
      - "8080:80"
    environment:
      - HostInfoFile=/app/host-info/host.txt
      - DataDir=/app/data
      - ConnectionStrings__AppDbContext=Server=db;Port=5432;Database=docker_learning_db;User Id=postgres;Password=zaQ@123456!;
    networks:
      - apps
    volumes:
      - ./docker/volumes/host-info:/app/host-info:ro
      - data:/app/data

  web-app:
    build:
      context: ./my-fe-app
    environment:
      - API=http://web-api
      - NEXT_PUBLIC_API=http://localhost:8080
    ports:
      - "3000:80"
    networks:
      - apps

  web-app-static:
    build:
      context: ./my-fe-app-static
    ports:
      - "3001:80"
    networks:
      - apps

  docker-dev-env:
    image: node:21-alpine3.18
    ports:
      - "3002:3000"
    networks:
      - apps
    tty: true
    stdin_open: true
    volumes:
      - ./my-fe-app-static:/workspace/my-fe-app-static
      - /workspace/my-fe-app-static/node_modules

networks:
  apps:

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/volumes/data
