services:
  web-api:
    image: k8s-learning.docker.io/web-api:1.0.0
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.0
    ports:
      - 8080:8080

  web-api-1:
    image: k8s-learning.docker.io/web-api:1.0.1
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.1
    ports:
      - 8080:8080

  web-api-2:
    image: k8s-learning.docker.io/web-api:1.0.2
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.2
        - HAS_ERROR=true
    ports:
      - 8080:8080
