services:
  web-api:
    image: k8s-learning.docker.io/web-api:1.0.0
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.0

  web-api-1:
    image: k8s-learning.docker.io/web-api:1.0.1
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.1

  web-api-2:
    image: k8s-learning.docker.io/web-api:1.0.2
    build:
      context: .
      dockerfile: ./K8sLearning.WebApi/Dockerfile
      args:
        - VERSION=1.0.2
        - HAS_ERROR=true

  web-ui-client:
    image: k8s-learning.docker.io/web-ui-client
    build:
      context: .
      dockerfile: ./K8sLearning.WebUiClient/Dockerfile

  worker:
    image: k8s-learning.docker.io/worker
    build:
      context: .
      dockerfile: ./K8sLearning.Worker/Dockerfile
